sonar.projectKey=NHSDigital_NRLF
sonar.organization=nhsdigital
sonar.projectName=NRLF

sonar.python.version=3.12

sonar.sources=.
sonar.exclusions=scripts/**
sonar.tests=.
sonar.tests.inclusions=**/tests/**
sonar.coverage.exclusions=scripts/**, tests/**, **/tests/**
sonar.cpd.exclusions=tests/**, **/tests/**

sonar.python.coverage.reportPaths=dist/test-coverage.xml
