sonar.projectKey=NHSDigital_NRLF
sonar.organization=nhsdigital
sonar.projectName=NRLF

sonar.python.version=3.12

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/tests/**
sonar.coverage.inclusions=**/*.py
sonar.coverage.exclusions=scripts/**,tests/**, **/tests/**, **/*_schemas.py
sonar.cpd.exclusions=tests/**, **/tests/**, **/*_schemas.py

sonar.python.coverage.reportPaths=dist/test-coverage.xml
