sonar.projectKey=NHSDigital_NRLF
sonar.organization=nhsdigital
sonar.projectName=NRLF

sonar.python.version=3.12.10

sonar.exclusions=scripts/**
sonar.coverage.exclusions=scripts/**, test/**, **/tests/**
sonar.cpd.exclusions=tests/**, **/tests/**

sonar.python.coverage.reportPaths=dist/test-coverage.xml

# Exclude snomed urls as being unsafe
sonar.issue.ignore.multicriteria=exclude_snomed_urls
sonar.issue.ignore.multicriteria.exclude_snomed_urls.ruleKey=python:S5332
sonar.issue.ignore.multicriteria.exclude_snomed_urls.pattern=**http://snomed\.info(/sct)?**
