name: Switch Active Stack
run-name: Switch active stack to ${{ inputs.stack_name }} in ${{ inputs.environment }} by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to activate the stack in"
        required: true
        default: "dev"
        type: environment

      stack_name:
        description: Name of stack to activate
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: write

jobs:
  activate-stack:
    name: Activate ${{ inputs.stack_name }} for ${{ inputs.environment }}
    runs-on: codebuild-nhsd-nrlf-ci-build-project-${{ github.run_id }}-${{ github.run_attempt }}
    environment: ${{ inputs.environment }}

    steps:
      - name: Git clone - ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup environment
        run: |
          echo "${HOME}/.asdf/bin" >> $GITHUB_PATH
          poetry install --no-root

      - name: Configure Management Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.MGMT_ROLE_ARN }}
          role-session-name: github-actions-ci-${{ inputs.environment }}-${{ github.run_id}}

      - name: Get current environment config
        run: |
          poetry run python ./scripts/get_env_config.py all ${{ inputs.environment }}

      - name: Activate Stack
        run: |
          poetry run python ./scripts/activate_stack.py ${{ inputs.stack_name }} ${{ inputs.environment }}
