name: Build NRL Project on Environment
run-name: Build NRL Project on ${{ inputs.environment || 'dev' }}
permissions:
  id-token: write
  contents: read
  actions: write

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "The environment to deploy changes to"
        default: "dev"
        required: true

jobs:
  build:
    name: Build - ${{ github.ref }}
    runs-on: codebuild-nhsd-nrlf-ci-build-project-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Git clone - ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup environment
        run: |
          echo "${HOME}/.asdf/bin" >> $GITHUB_PATH
          poetry install --no-root

      - name: Run Linting
        run: make lint

      - name: Run Unit Tests
        run: make test

      - name: Build Project
        run: make build

      - name: Configure Management Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a #v4.3.1
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.MGMT_ROLE_ARN }}
          role-session-name: github-actions-ci-${{ inputs.environment || 'dev' }}-${{ github.run_id }}

      - name: Add S3 Permissions to Lambda
        run: |
          account=$(echo '${{ inputs.environment || 'dev' }}' | cut -d '-' -f1)
          inactive_stack=$(poetry run python ./scripts/get_env_config.py inactive-stack ${{ inputs.environment || 'dev' }})
          make get-s3-perms ENV=${account} TF_WORKSPACE_NAME=${inactive_stack}

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/*.zip
            !dist/nrlf_permissions.zip

      - name: Save NRLF Permissions cache
        uses: actions/cache/save@v4
        with:
          key: ${{ github.run_id }}-nrlf-permissions
          path: dist/nrlf_permissions.zip

  sbom:
    name: Generate SBOM - ${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Git clone - ${{ github.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Generate SBOM
        uses: nhs-england-tools/trivy-action/sbom-scan@v1.4.0
        with:
          repo-path: "./"
